// Generated by scripts/build_js_bridge.mjs from js/src/llama_webgpu_bridge.d.ts.
// Do not edit this file directly; update js/src/ and run npm run build:js.
export type LlamaCoreModuleFactory = (options?: Record<string, unknown>) => unknown | Promise<unknown>;

export interface LlamaWebGpuBridgeConfig {
  coreModuleUrl?: string;
  coreModuleUrlMem64?: string;
  wasmUrl?: string;
  wasmUrlMem64?: string;
  coreModuleFactory?: LlamaCoreModuleFactory | Promise<LlamaCoreModuleFactory>;
  workerUrl?: string;
  disableWorker?: boolean;
  preferMemory64?: boolean;
  workerRequestTimeoutMs?: number;
  workerInitTimeoutMs?: number;
  workerModelLoadTimeoutMs?: number;
  workerMmprojLoadTimeoutMs?: number;
  workerCompletionTimeoutMs?: number;
  workerTextToSpeechTimeoutMs?: number;
  workerGenerationStallTimeoutMs?: number;
  coreInitTimeoutMs?: number;
  cacheName?: string;
  threads?: number;
  threadsBatch?: number;
  threadPoolSize?: number;
  nBatch?: number;
  nUbatch?: number;
  nGpuLayers?: number;
  userAgent?: string;
  remoteFetchThresholdBytes?: number;
  remoteFetchChunkBytes?: number;
  mediaMaxImagePixels?: number;
  mediaMaxImageEdge?: number;
  disableImageDownscale?: boolean;
  allowAutoRemoteFetchBackend?: boolean;
  logLevel?: string | number;
  [key: string]: unknown;
}

export interface BridgeProgressEvent {
  loaded?: number;
  total?: number;
  shard?: number;
  shards?: number;
  url?: string;
  [key: string]: unknown;
}

export interface LoadModelOptions {
  progressCallback?: (progress: BridgeProgressEvent) => void;
  signal?: AbortSignal;
  remoteFetchThresholdBytes?: number;
  remoteFetchChunkBytes?: number;
  /** Load the model's MTP layers, which `draft-mtp` speculative decoding needs. Defaults to false. */
  loadMtp?: boolean;
  /** Rollback snapshots per sequence, llama.cpp's `n_rs_seq`: a model with recurrent state needs at least the draft length for `draft-*` speculative decoding. Defaults to 0. */
  speculativeRollbackTokenMax?: number;
  [key: string]: unknown;
}

/** Options for `loadDraftModel`. */
export interface DraftModelLoadOptions {
  /** Receives `{ loaded, total }` download progress. */
  progressCallback?: (progress: BridgeProgressEvent) => void;
  /** Cancels the download. */
  signal?: AbortSignal;
  /** Use Cache Storage for the draft GGUF. Defaults to true. */
  useCache?: boolean;
  /** Refetch even when Cache Storage holds the draft GGUF. */
  force?: boolean;
}

/** The loaded draft model. */
export interface DraftModelInfo {
  /** The GGUF's `general.architecture`. */
  architecture: string;
  /** `draft-dflash` or `draft-dspark` for a DFlash-architecture draft, as llama.cpp reads its metadata; absent otherwise. */
  strategy?: 'draft-dflash' | 'draft-dspark';
}

export type TokenEventEncoding = 'bytes' | 'text' | (string & {});

export type CompletionMediaData = ArrayBuffer | ArrayBufferView | readonly number[];

export type CompletionImagePart = {
  type: 'image';
  width?: number;
  height?: number;
} & (
  | { bytes: CompletionMediaData; url?: string }
  | { bytes?: CompletionMediaData; url: string }
);

export type CompletionAudioPart = {
  type: 'audio';
} & (
  | { samples: CompletionMediaData; bytes?: CompletionMediaData; url?: string }
  | { samples?: CompletionMediaData; bytes: CompletionMediaData; url?: string }
  | { samples?: CompletionMediaData; bytes?: CompletionMediaData; url: string }
);

export type CompletionMediaPart = CompletionImagePart | CompletionAudioPart;

/** Why a completion stopped. */
export type CompletionFinishReason = 'stop' | 'length' | 'cancelled';

/** Token counts and timings of one completion. */
export interface CompletionUsage {
  /** Prompt tokens in the context when generation started, including `cachedPromptTokens`; context positions for a multimodal prompt. */
  promptTokens: number;
  /** Leading prompt tokens kept from the previous prompt or a loaded state instead of being evaluated again; 0 for a multimodal prompt. */
  cachedPromptTokens: number;
  /** Generated tokens in the returned text; the end-of-generation token is not counted. */
  completionTokens: number;
  /** Milliseconds from the runtime starting the completion to its first streamed text; null when it streamed none. */
  timeToFirstTokenMs: number | null;
  /** Milliseconds from the runtime starting the completion to its end. */
  durationMs: number;
  /** `stop` at an end-of-generation token, `length` at `nPredict` or the context limit, `cancelled` after `cancel()` or an abort. */
  finishReason: CompletionFinishReason;
  /** Speculative decoding counters; present only when the completion used `speculativeDecoding`. */
  speculative?: SpeculativeDecodingUsage;
}

/** Speculative decoding counters of one completion. */
export interface SpeculativeDecodingUsage {
  /** Draft tokens proposed. */
  draftTokens: number;
  /** Draft tokens the target model accepted. */
  acceptedDraftTokens: number;
  /** Draft steps attempted, including those that proposed no tokens. */
  draftAttempts: number;
  /** Target-model tokens decoded to verify drafts. */
  verifyTokens: number;
  /** Target-model tokens decoded again after restoring a recurrent-state checkpoint. */
  replayTokens: number;
}

/** llama.cpp speculative decoding strategies, by their `--spec-type` names. */
export type SpeculativeDecodingStrategy =
  | 'draft-simple'
  | 'draft-eagle3'
  | 'draft-mtp'
  | 'draft-dflash'
  | 'draft-dspark'
  | 'ngram-simple'
  | 'ngram-map-k'
  | 'ngram-map-k4v'
  | 'ngram-mod'
  | 'ngram-cache';

/** An n-gram cache file from `llama-lookup-create`: a URL, or its bytes. */
export type NgramCacheSource = string | ArrayBuffer | ArrayBufferView;

/** llama.cpp speculative decoding for one completion. Omitted numbers use llama.cpp's defaults. */
export interface SpeculativeDecodingOptions {
  /** Strategies to combine: any n-gram strategies plus at most one `draft-*` strategy. */
  strategies: readonly SpeculativeDecodingStrategy[];
  /** Maximum draft tokens per step, from 0, resolved as native llamadart resolves it: `draft-*` strategies use this or 3, `ngram-simple`/`ngram-map-k`/`ngram-map-k4v` use `ngramSizeM` or 48, `ngram-mod` uses `ngramTokenMax`, then this, then 64, and `ngram-cache` uses this or 8. The largest applies; 0 becomes 64. The resolved value must not exceed the context size. */
  draftTokenMax?: number;
  /** Minimum draft tokens a draft model must propose, from 0 to the resolved `draftTokenMax`. Needs a `draft-*` strategy. */
  draftTokenMin?: number;
  /** Minimum draft-token probability, from 0 to 1. Needs a `draft-*` strategy. */
  minProbability?: number;
  /** Draft split probability, from 0 to 1. Needs a `draft-*` strategy. */
  draftSplitProbability?: number;
  /** Lookup n-gram size for `ngram-simple`, `ngram-map-k` and `ngram-map-k4v`, from 1 to 65535. */
  ngramSizeN?: number;
  /** Draft m-gram size for `ngram-simple`, `ngram-map-k` and `ngram-map-k4v`, from 1 to 65535; also their draft length. */
  ngramSizeM?: number;
  /** Minimum lookup hits before `ngram-map-k`/`ngram-map-k4v` propose an m-gram, from 1 to 65535. */
  ngramMinHits?: number;
  /** Lookup length for `ngram-mod`, from 1 to 65535. */
  ngramMatch?: number;
  /** Minimum draft length for `ngram-mod`, from 0. */
  ngramTokenMin?: number;
  /** Maximum draft length for `ngram-mod`, from 0 to the context size; defaults to `draftTokenMax` when `ngram-mod` is enabled. */
  ngramTokenMax?: number;
  /** Static n-gram cache for `ngram-cache`. */
  ngramCacheStatic?: NgramCacheSource;
  /** Dynamic n-gram cache for `ngram-cache`, read once; the bridge does not write it back. */
  ngramCacheDynamic?: NgramCacheSource;
}

export interface CompletionOptions {
  onToken?: (piece: string | Uint8Array, currentText: string | null) => void;
  /** Called at most once, with the usage of the last attempt whose generation returned, before `createCompletion` resolves or rejects with an `AbortError`. Not called when no generation returned: other rejections, a skipped multimodal warmup, or a worker failure after a cancel. */
  onUsage?: (usage: CompletionUsage) => void;
  signal?: AbortSignal;
  warmup?: boolean;
  emitCurrentTextOnToken?: boolean;
  tokenEventEncoding?: TokenEventEncoding;
  tokenEventFlushMs?: number;
  tokenEventFlushChars?: number;
  nPredict?: number;
  mediaMaxPredict?: number;
  parts?: readonly CompletionMediaPart[];
  temp?: number;
  topK?: number;
  topP?: number;
  /** Min-P threshold from 0 to 1, applied after top-p; 0, the default, disables it. A value outside that range rejects. */
  minP?: number;
  penalty?: number;
  /** Subtracted once from the logit of each token among this completion's last 64 tokens; prompt tokens do not count. 0, the default, disables it. A value that is not finite as a 32-bit float rejects. */
  presencePenalty?: number;
  grammar?: string;
  seed?: number;
  /** Caps the tokens generated inside each reasoning block; text-only prompts. */
  thinkingBudget?: ThinkingBudgetOptions | null;
  /** Drafts tokens and verifies them with the loaded model; text-only prompts without `grammar` or `thinkingBudget`. With greedy sampling the output matches a completion without it. */
  speculativeDecoding?: SpeculativeDecodingOptions | null;
}

/** llama.cpp's reasoning budget: after `maxTokens` tokens inside a reasoning block, plus any that finish a UTF-8 character, the sampler forces `forcedMessage` and `endTag`. A grammar pauses after `startTag` until `endTag` completes. */
export interface ThinkingBudgetOptions {
  /** Integer from 0 to 2147483647. 0 forces the end as soon as a block opens, or at once when the prompt ends inside one. */
  maxTokens: number;
  /** Opens a reasoning block, such as `<think>`. */
  startTag: string;
  /** Closes a reasoning block, such as `</think>`. */
  endTag: string;
  /** Text forced before `endTag` when the budget runs out; empty by default. */
  forcedMessage?: string;
}

/** Completion options the loaded core applies. Every flag is false until a model load initializes the core. */
export interface CompletionCapabilities {
  /** `CompletionOptions.presencePenalty` is applied. */
  presencePenalty: boolean;
  /** `CompletionOptions.minP` is applied. */
  minP: boolean;
  /** `CompletionOptions.thinkingBudget` is applied. */
  thinkingBudget: boolean;
  /** Each speculative strategy the loaded models can run now: `draft-mtp` needs a model loaded with `loadMtp` that has MTP layers, and the other `draft-*` strategies a matching `loadDraftModel` draft. */
  speculativeDecoding: Record<SpeculativeDecodingStrategy, boolean>;
}

export interface EmbedOptions {
  normalize?: boolean;
}

export interface NextTokenScoreOptions {
  /** Token ids to score, in the order the result lists them. */
  candidates?: ArrayLike<number>;
  /** How many of the most probable tokens to return; 0 returns none. */
  topK?: number;
  /** Reuse the KV cache prefix shared with the previous prompt. Defaults to true. */
  reusePromptPrefix?: boolean;
}

export interface ScoredToken {
  token: number;
  /** The token's text as raw bytes; a piece may split a UTF-8 sequence. */
  bytes: Uint8Array;
  /** Natural-log probability; -Infinity when it is zero or a non-finite logit makes it undefined. */
  logprob: number;
}

export interface NextTokenScores {
  candidates: ScoredToken[];
  top: ScoredToken[];
  promptTokens: number;
}

export interface TextToSpeechCapabilities {
  apiVersion: number;
  supported: boolean;
  modelType: number;
  capabilities: number;
  supportsLanguage: boolean;
  supportsSpeakerReference: boolean;
  sampleRate: number;
  channels: number;
  reason: string;
}

export interface TextToSpeechProgress {
  state: number;
  promptTokensRemaining: number;
  framesGenerated: number;
  truncated: boolean;
}

export interface TextToSpeechOptions {
  text: string;
  language?: string;
  speakerAudio?: Uint8Array | ArrayBuffer | ArrayLike<number>;
  promptBatchSize?: number;
  maxFrames?: number;
  topK?: number;
  topP?: number;
  minP?: number;
  temperature?: number;
  seed?: number;
  signal?: AbortSignal;
  onProgress?: (progress: TextToSpeechProgress) => void;
}

export interface TextToSpeechResult {
  pcm: Float32Array;
  sampleRate: number;
  channels: number;
  sampleCount: number;
  framesGenerated: number;
  truncated: boolean;
}

export interface DecisionCapabilities {
  apiVersion: number;
  supported: boolean;
  /** Why the loaded model cannot run decision heads; absent when supported. */
  reason?: string;
}

export interface DecisionHeadOptions {
  /** Laya `rl_agent_config.json` text; omit to read the head's `laya.config` metadata. */
  configJson?: string | null;
  /** Download progress of a URL head, in bytes. */
  onProgress?: (progress: { loaded: number; total: number }) => void;
}

export interface DecisionHeadInfo {
  apiVersion: number;
  handle: number;
  hiddenSize: number;
  clsToken: number;
  sepToken: number;
  maskToken: number;
  maskText: string;
  configJson: string;
  deviceName: string;
}

/** 0 = choice, 1 = score, 2 = noul. */
export type DecisionQuestionType = 0 | 1 | 2;

export interface DecisionSequence {
  tokens: Int32Array | readonly number[];
  /** Token indexes of the option markers, in option order. */
  markers: Int32Array | readonly number[];
  questionType: DecisionQuestionType;
}

export interface DecisionOutput {
  /** One raw logit per marker. */
  logits: Float32Array;
  actLogits: Float32Array;
}

export interface LoraAdapterCapabilities {
  apiVersion: number;
  supported: boolean;
  /** Why this bridge cannot load LoRA adapters; absent when supported. */
  reason?: string;
}

export interface LoraAdapterLoadOptions {
  /** Download progress of a URL adapter, in bytes. */
  progressCallback?: (progress: BridgeProgressEvent) => void;
  /** Cancels the download of a URL adapter. A load whose adapter already reached the runtime still completes. */
  signal?: AbortSignal;
  /** Read and store a URL adapter in the Cache API, as models are. Defaults to true. */
  useCache?: boolean;
  /** Cache API cache name for a URL adapter; defaults to the bridge's `cacheName`. */
  cacheName?: string;
}

export interface LoraAdapterInfo {
  /** Identifies the adapter until its model is unloaded or replaced. */
  handle: number;
}

export type ModelMetadata = Record<string, unknown>;

export interface StateLoadResult {
  tokens: number[];
}

export function enableBridgeWorkerHost(): void;

/**
 * Runtime-backed async operations use a per-instance FIFO queue. Queued aborts
 * skip dispatch without cancelling the active owner; `cancel` and `setLogLevel`
 * remain out of band; disposal rejects queued/new work while active work settles
 * first. See docs/api.md "Operation serialization".
 */
export class LlamaWebGpuBridge {
  static supportsSafariAdaptiveGpu: boolean;
  /** `true` when `createCompletion` accepts `onUsage`. Bridges before v0.1.54 lack it; through v0.1.52 their worker mode rejects a function option with a `DataCloneError`. */
  static supportsCompletionUsage: boolean;

  constructor(config?: LlamaWebGpuBridgeConfig);

  loadModelFromUrl(url: string | string[], options?: LoadModelOptions): Promise<unknown>;
  prefetchModelToCache(url: string | string[], options?: LoadModelOptions): Promise<unknown>;
  evictModelFromCache(url: string | string[], options?: Record<string, unknown>): Promise<unknown>;

  createCompletion(prompt: string, options?: CompletionOptions): Promise<string>;
  getCompletionCapabilities(): Promise<CompletionCapabilities>;
  /** Loads a draft GGUF for `draft-simple`, `draft-eagle3`, `draft-dflash` or `draft-dspark`, replacing any draft. A model load unloads it. */
  loadDraftModel(url: string, options?: DraftModelLoadOptions): Promise<DraftModelInfo>;
  unloadDraftModel(): Promise<void>;
  tokenize(text: string, addSpecial?: boolean): Promise<number[]>;
  detokenize(tokens: number[] | ArrayLike<number>, special?: boolean): Promise<string>;
  applyChatTemplate(
    messages: Array<Record<string, unknown>>,
    addAssistant?: boolean,
    customTemplate?: string | null,
  ): Promise<string>;

  stateSaveFile(path: string, tokens?: number[] | ArrayLike<number>): Promise<true>;
  stateLoadFile(path: string, tokenCapacity?: number): Promise<StateLoadResult>;
  stateSaveBytes(tokens?: number[] | ArrayLike<number>): Promise<Uint8Array>;
  stateLoadBytes(bytes: Uint8Array | ArrayBuffer | ArrayLike<number>, tokenCapacity?: number): Promise<StateLoadResult>;

  embed(text: string, options?: EmbedOptions): Promise<number[]>;
  embedBatch(texts: string[], options?: EmbedOptions): Promise<number[][]>;
  scoreNextToken(prompt: string, options?: NextTokenScoreOptions): Promise<NextTokenScores>;

  loadMultimodalProjector(url: string): Promise<unknown>;
  unloadMultimodalProjector(): Promise<unknown>;
  supportsVision(): boolean;
  supportsAudio(): boolean;
  getTextToSpeechCapabilities(): Promise<TextToSpeechCapabilities>;
  synthesizeSpeech(options: TextToSpeechOptions): Promise<TextToSpeechResult>;
  getDecisionCapabilities(): Promise<DecisionCapabilities>;
  loadDecisionHead(
    source: string | ArrayBuffer | ArrayBufferView,
    options?: DecisionHeadOptions,
  ): Promise<DecisionHeadInfo>;
  runDecision(handle: number, sequences: readonly DecisionSequence[]): Promise<DecisionOutput[]>;
  freeDecisionHead(handle: number): Promise<void>;
  getLoraAdapterCapabilities(): Promise<LoraAdapterCapabilities>;
  loadLoraAdapter(
    source: string | ArrayBuffer | ArrayBufferView,
    options?: LoraAdapterLoadOptions,
  ): Promise<LoraAdapterInfo>;
  setLoraAdapter(handle: number, scale?: number): Promise<void>;
  removeLoraAdapter(handle: number): Promise<void>;
  clearLoraAdapters(): Promise<void>;

  getModelMetadata(): ModelMetadata | null;
  getContextSize(): number;
  isGpuActive(): boolean;
  getBackendName(): string;
  setLogLevel(level: string | number): void;
  cancel(): void;
  dispose(): Promise<void>;
}

declare global {
  interface Window {
    LlamaWebGpuBridge?: typeof LlamaWebGpuBridge;
  }
}
